/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as ApiBotStatusRouteImport } from './routes/api/bot/status'
import { Route as ApiBotForceStopRouteImport } from './routes/api/bot/force-stop'
import { Route as ApiBotCompleteRouteImport } from './routes/api/bot/complete'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppMeetingMeetingIdRouteImport } from './routes/_app/meeting/$meetingId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const ApiBotStatusRoute = ApiBotStatusRouteImport.update({
  id: '/api/bot/status',
  path: '/api/bot/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotForceStopRoute = ApiBotForceStopRouteImport.update({
  id: '/api/bot/force-stop',
  path: '/api/bot/force-stop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotCompleteRoute = ApiBotCompleteRouteImport.update({
  id: '/api/bot/complete',
  path: '/api/bot/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMeetingMeetingIdRoute = AppMeetingMeetingIdRouteImport.update({
  id: '/meeting/$meetingId',
  path: '/meeting/$meetingId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/history': typeof AppHistoryRoute
  '/meeting/$meetingId': typeof AppMeetingMeetingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bot/complete': typeof ApiBotCompleteRoute
  '/api/bot/force-stop': typeof ApiBotForceStopRoute
  '/api/bot/status': typeof ApiBotStatusRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/history': typeof AppHistoryRoute
  '/': typeof AppIndexRoute
  '/meeting/$meetingId': typeof AppMeetingMeetingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bot/complete': typeof ApiBotCompleteRoute
  '/api/bot/force-stop': typeof ApiBotForceStopRoute
  '/api/bot/status': typeof ApiBotStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/': typeof AppIndexRoute
  '/_app/meeting/$meetingId': typeof AppMeetingMeetingIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bot/complete': typeof ApiBotCompleteRoute
  '/api/bot/force-stop': typeof ApiBotForceStopRoute
  '/api/bot/status': typeof ApiBotStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/history'
    | '/meeting/$meetingId'
    | '/api/auth/$'
    | '/api/bot/complete'
    | '/api/bot/force-stop'
    | '/api/bot/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/history'
    | '/'
    | '/meeting/$meetingId'
    | '/api/auth/$'
    | '/api/bot/complete'
    | '/api/bot/force-stop'
    | '/api/bot/status'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/history'
    | '/_app/'
    | '/_app/meeting/$meetingId'
    | '/api/auth/$'
    | '/api/bot/complete'
    | '/api/bot/force-stop'
    | '/api/bot/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBotCompleteRoute: typeof ApiBotCompleteRoute
  ApiBotForceStopRoute: typeof ApiBotForceStopRoute
  ApiBotStatusRoute: typeof ApiBotStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/bot/status': {
      id: '/api/bot/status'
      path: '/api/bot/status'
      fullPath: '/api/bot/status'
      preLoaderRoute: typeof ApiBotStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot/force-stop': {
      id: '/api/bot/force-stop'
      path: '/api/bot/force-stop'
      fullPath: '/api/bot/force-stop'
      preLoaderRoute: typeof ApiBotForceStopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot/complete': {
      id: '/api/bot/complete'
      path: '/api/bot/complete'
      fullPath: '/api/bot/complete'
      preLoaderRoute: typeof ApiBotCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/meeting/$meetingId': {
      id: '/_app/meeting/$meetingId'
      path: '/meeting/$meetingId'
      fullPath: '/meeting/$meetingId'
      preLoaderRoute: typeof AppMeetingMeetingIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMeetingMeetingIdRoute: typeof AppMeetingMeetingIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppIndexRoute: AppIndexRoute,
  AppMeetingMeetingIdRoute: AppMeetingMeetingIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBotCompleteRoute: ApiBotCompleteRoute,
  ApiBotForceStopRoute: ApiBotForceStopRoute,
  ApiBotStatusRoute: ApiBotStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
